# Generated by Django 4.1.2 on 2022-11-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppViajes', '0003_alter_agencia_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='capacidad',
            field=models.BooleanField(default=True),
        ),
    ]
