# Generated by Django 4.1.2 on 2022-11-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppViajes', '0004_alter_tour_capacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
    ]
