# Generated by Django 4.1.2 on 2022-11-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppViajes', '0005_alter_tour_capacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='capacidad',
            field=models.IntegerField(),
        ),
    ]
